// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASP2Ddrt6UxxpKOa34SmaqeinWW05WL2A',
    appId: '1:726257704783:web:ce74c527723c4c946e2f3a',
    messagingSenderId: '726257704783',
    projectId: 'hero-games-case-64a39',
    authDomain: 'hero-games-case-64a39.firebaseapp.com',
    storageBucket: 'hero-games-case-64a39.appspot.com',
    measurementId: 'G-3002J4MQZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA93UKW_w9NEuI-hEf3XNxAKw5qIya3WZM',
    appId: '1:726257704783:android:d4047457f83511a56e2f3a',
    messagingSenderId: '726257704783',
    projectId: 'hero-games-case-64a39',
    storageBucket: 'hero-games-case-64a39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0_o2DqkSlyDNgIg3ekj8AN8TFzkKPSt0',
    appId: '1:726257704783:ios:1667c5e44d1a0b706e2f3a',
    messagingSenderId: '726257704783',
    projectId: 'hero-games-case-64a39',
    storageBucket: 'hero-games-case-64a39.appspot.com',
    iosBundleId: 'com.example.heroGamesCase',
  );
}
